apiVersion: v1
kind: Namespace
metadata:
  name: kcna-lab
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: kcna-lab
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "10"
