apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
  namespace: product-catalog
  labels:
    app: product-catalog
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
